name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]


jobs:
  explore:
    runs-on: ubuntu-latest
    name: Name
    steps:
    - env:
        VAR: val
      run: |
        echo ${{ job.name }} ${{ job.status }}
